baseURL = "/"
languageCode = "en-us"
title = "Bianchi Chartered Accountants"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""
  author = "Bianchi Chartered Accountants"

  [params.logo]
    mobile = "images/logo.jpg"
    mobile_height = "45px"
    alt = "Bianchi Chartered Accountants"

  [params.acalogo]
    mobile = "images/icaew_ciot.png"
    mobile_height = "25px"
    desktop = "images/icaew_ciot.png"
    desktop_height = "40px" 
    alt = "ACA CTA logo"

  [params.homepage_meta_tags]
    meta_description = "We offer accounting and tax advice, planning and preparation services tailored to suit individuals and businesses in the North West."
    meta_og_title = "Bianchi Chartered Accountants"
    meta_og_type = "website"
    meta_og_url = "https://www.bianchiaccountants.co.uk/"
    meta_og_description = "We offer accounting and tax advice, planning and preparation services tailored to suit individuals and businesses in the North West."

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
